### PR TITLE
Add favicon `link` support

### PR DESCRIPTION
**Pull request by SpainTrain**
- Add new prop `favicon` to take url to favicon

---

This change is [Reviewable](https://reviewable.io/reviews/venmo/react-html-document/12)

### CODE REVIEW

**Comment by SpainTrain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/venmo/react-html-document/12)*

**Comment by SpainTrain** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/venmo/react-html-document/12)*

**Comment by SpainTrain** [comment]
@xavierelopez @sranso @rix501 

Anything I can do to help get this guy merged/released? :-)

**Review by xavierelopez — APPROVED** [review]
Thanks @SpainTrain, looks good.

**Comment by xavierelopez** [comment]
This was included in the 3.1.0 release. Thanks again.

**Comment by SpainTrain** [comment]
Thanks! :blush:

**Pull request merged**
